### ISSUE TITLE
Error in filespy watcher

### ISSUE THREAD

**Issue by ghivert** [pta2002/gleam-radiate#1]
Hi !

I tried to setup an auto-reload server using Mist in Gleam, and I could not achieve it to work. I'm on a MacBook M2 right now, and after some digging in the code, it looks like `filespy` is [warning here with `filespy.Modified`, but never `filespy.Closed`](https://github.com/pta2002/gleam-radiate/blob/e553f2568ea1c2cf0ae75dc4adf98cec1ed7d7e3/src/radiate.gleam#L110).

After copying `radiate` locally and modify that line to `filespy.Closed | filespy.Modified -> {`, it's working perfectly! I don't really know why events are not the same, I suppose it's due to OS differences. 

Do you want me to open a PR for this or maybe you're planning to expand the support of `filespy` in the future?

For context, main file.

<details><summary>Details</summary>
<p>

```gleam
import gleam/erlang/process
import gleam/io
import mist
import radiate

fn print_radiate_update(_state: state, path: String) {
  io.println("Change in " <> path <> ", reloading")
}

pub fn main() {
  let assert Ok(_) =
    radiate.new()
    |> radiate.add_dir(".")
    |> radiate.add_dir("src")
    |> radiate.on_reload(print_radiate_update)
    |> radiate.start()

  let assert Ok(_) =
    handle_request // My custom handler
    |> mist.new()
    |> mist.port(3000)
    |> mist.start_http()

  process.sleep_forever()
}
```

</p>
</details>

**Comment by pta2002** [comment]
Hey, please open the PR! I remember when I wrote that initially it was basically all based off testing out the file events, but since I didn't have a mac to test with I just assumed it'd be the same as linux, therefore the weirdness.
